vich_uploader:
    db_driver: orm
    
    metadata:
        type: attribute

    mappings:
        blog_thumbnail:
            uri_prefix: /upload/images/blog
            upload_destination: '%kernel.project_dir%/public/upload/images/blog'
            namer: 'namer.blog_thumbnail'
            
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false
